# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckImage < Formula
  desc "Validate container images against security and operational standards"
  homepage "https://github.com/jarfernandez/check-image"
  version "0.18.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.18.0/check-image_0.18.0_darwin_amd64.tar.gz"
      sha256 "042a4cee7e76eff6186adc00d90ddd905e00700fb9b4a5243211685fed39b2bd"

      define_method(:install) do
        bin.install "check-image"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.18.0/check-image_0.18.0_darwin_arm64.tar.gz"
      sha256 "223ba8a782e40d4190cf99b774cbae9a74e23bc14d11f98d9b6a17d4bacdbf89"

      define_method(:install) do
        bin.install "check-image"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.18.0/check-image_0.18.0_linux_amd64.tar.gz"
      sha256 "798762af7014ba11e154999e30550c2cba65183608b9972ec837fb276c8de3ce"
      define_method(:install) do
        bin.install "check-image"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.18.0/check-image_0.18.0_linux_arm64.tar.gz"
      sha256 "797037cff0b18268d5208cfdb17b77b94b54e37400b8f07e7fadd9365551cfa7"
      define_method(:install) do
        bin.install "check-image"
      end
    end
  end

  test do
    system "#{bin}/check-image", "version", "--short"
  end
end
