# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckImage < Formula
  desc "Validate container images against security and operational standards"
  homepage "https://github.com/jarfernandez/check-image"
  version "0.20.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.20.10/check-image_0.20.10_darwin_amd64.tar.gz"
      sha256 "ca6f3a0df7e6681de504c6accbd1cf9b093b3457f7b6e22e02a83323ff629232"

      define_method(:install) do
        bin.install "check-image"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.20.10/check-image_0.20.10_darwin_arm64.tar.gz"
      sha256 "da847b1bed7c2154206c610a82a4dd4755bb402a18791627670bd269d57ed022"

      define_method(:install) do
        bin.install "check-image"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.20.10/check-image_0.20.10_linux_amd64.tar.gz"
      sha256 "d7cfec1cb58bd16fd06efb7148c52734d3979131f8490f3b94d7223fd0927e1a"
      define_method(:install) do
        bin.install "check-image"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.20.10/check-image_0.20.10_linux_arm64.tar.gz"
      sha256 "403b2a3a8ade79216c392e9ac3bf3d7cd997c9d156ef7c337b089e19882a7c12"
      define_method(:install) do
        bin.install "check-image"
      end
    end
  end

  test do
    system "#{bin}/check-image", "version", "--short"
  end
end
