# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CheckImage < Formula
  desc "Validate container images against security and operational standards"
  homepage "https://github.com/jarfernandez/check-image"
  version "0.21.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.21.1/check-image_0.21.1_darwin_amd64.tar.gz"
      sha256 "6d750f1fe188b96c787f257493b006473e8f9c0169574ae7d786c17441db05dc"

      define_method(:install) do
        bin.install "check-image"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.21.1/check-image_0.21.1_darwin_arm64.tar.gz"
      sha256 "68b5302dd0a72ee9f3afdf13eddc3d06528bbac0f51b1b786bc3e53193fc6584"

      define_method(:install) do
        bin.install "check-image"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.21.1/check-image_0.21.1_linux_amd64.tar.gz"
      sha256 "e121db26e0bb875f441a655d46171f8914e369b8643671884c9af427417aec3d"
      define_method(:install) do
        bin.install "check-image"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jarfernandez/check-image/releases/download/v0.21.1/check-image_0.21.1_linux_arm64.tar.gz"
      sha256 "82a1dd2166d61b11d59ce2195a3e61f969d70f399fb69c9f3eef218f3e740907"
      define_method(:install) do
        bin.install "check-image"
      end
    end
  end

  test do
    system "#{bin}/check-image", "version", "--short"
  end
end
